# Rebuild the app when Go files (or go.mod/sum) change, then restart it.
root = "."
tmp_dir = "air"

[build]
cmd = "go build -o ./air/app ./cmd/server"  # adjust package/path if different
bin = "air/app"
full_bin = ""
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["air", "bin", "vendor", ".git"]
exclude_file = []
exclude_regex = ["_test\\.go"]
delay = 1000
stop_on_error = true
send_interrupt = true
kill_delay = "500ms"

[log]
time = true

[color]
main = "yellow"
watcher = "cyan"
build = "green"
runner = "magenta"

[misc]
clean_on_exit = true
