





services:
  backend:
    image: backend:prod
    container_name: backend

    ports:
      - "8080:8080"
      
    # Color configuration
    tty: true           # allocate a TTY (critical for colors)
    environment:
      TERM: xterm-256color    
      DATABASE_URL: postgres://admin:password@database:5432/main
      FIREBASE_CREDENTIALS_FILE: /app/firebase_sa.json
      WEBSITE_URL: http://website:5173
    
    networks: [appnet]

    volumes:
      - $APPS_DIRECTORY/backend/firebase_sa.json:/app/firebase_sa.json

networks:
  appnet:
    driver: bridge
