name: build-push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      IMAGE_TAG: ${{ steps.tag.outputs.IMAGE_TAG }}

    steps:

      - name: Set APP_DIR env
        run: |
          echo "APP_DIR=workspace/apps/$(basename "$GITHUB_REPOSITORY")" >> "$GITHUB_ENV"

      - name: Checkout workspace repo
        uses: actions/checkout@v4
        with:
          repository: payway-bz/workspace
          path: workspace
          fetch-depth: 1

      # 2) Checkout the current repository into workspace/apps/<repo-name>
      - name: Checkout current repo into workspace/apps/<repo>
        uses: actions/checkout@v4
        with:
          path: ${{ env.APP_DIR }}
          fetch-depth: 1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure Docker to use the gcloud command-line tool as a credential helper
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Set docker image tag
        id: tag
        working-directory: ${{ env.APP_DIR }}
        run: echo "IMAGE_TAG=$(../../helpers/get-dev-tag)" >> "$GITHUB_OUTPUT"

      - name: Build docker image
        working-directory: ${{ env.APP_DIR }}
        run: ../../helpers/docker-build -t ${{ steps.tag.outputs.IMAGE_TAG }}

      - name: Push docker image
        working-directory: ${{ env.APP_DIR }}
        run: ../../helpers/docker-push -t ${{ steps.tag.outputs.IMAGE_TAG }}

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build

  #   steps:
  #     - name: Checkout infrastructure repository
  #       uses: actions/checkout@v2
  #       with:
  #         repository: express-drive/infrastructure
  #         token: ${{ secrets.ACTIONS_CREDENTIALS }}

  #     - name: Set up Git
  #       run: |
  #         git config --global user.name "github-actions[bot]"
  #         git config --global user.email "github-actions[bot]@users.noreply.github.com"

  #     - name: Set file path
  #       id: file_path
  #       run: echo "FILE_PATH=apps/staging/website-release.yaml" >> "$GITHUB_OUTPUT"

  #     - name: Update YAML file with new tag
  #       run: |
  #         NEW_TAG="${{ needs.build.outputs.IMAGE_TAG }}"
  #         FILE_PATH="${{ steps.file_path.outputs.FILE_PATH }}"
  #         echo "Inserting $NEW_TAG into $FILE_PATH"
  #         sed -i "s/\(tag: \).*\(# WORKER_REPLACE website-dev-tag\)/\1$NEW_TAG \2/" "$FILE_PATH"

  #     - name: Commit changes
  #       run: |
  #         git add .
  #         git commit -m "Automated website-production tag image update to ${{ needs.build.outputs.IMAGE_TAG }}"
  #         git push
